Import('env')

env = env.Clone()
env.Append(CPPPATH = '#/')

sources = '''
dict.c
eval.c
exception.c
lexer.c
math.c
parser.c
position.c
program_file.c
string_reader.c
yolo.c
'''.split()

program = env.Program(['test.c'] + sources + env.wsky_objects)
