Import('env')

env = env.Clone()
env.Append(CPPPATH = '#/')

sources = '''
tests.c
exception.c
program_file.c
str.c
string_reader.c
yolo.c
'''.split()

program = env.Program(sources + env.degat_objects)
