Import('env')

env = env.Clone()
env.Append(CPPPATH = '#/')

sources = '''
boolean.c
exception.c
float.c
function.c
integer.c
null.c
program_file.c
syntax_error_ex.c
scope.c
str.c
'''.split()

objects = env.Object(sources)
Return('objects')
