Import('env')

env = env.Clone()

sources = '''
attribute_error.c
boolean.c
class.c
exception.c
float.c
function.c
import_error.c
integer.c
instance_method.c
method.c
module.c
name_error.c
not_implemented_error.c
null.c
object.c
parameter_error.c
program_file.c
syntax_error_ex.c
scope.c
str.c
structure.c
type_error.c
value_error.c
'''.split()

objects = env.Object(sources)
Return('objects')
