Import('env')

env = env.Clone()
env.Append(CPPPATH = '#/')

sources = '''
ast.c
class_def.c
dict.c
eval.c
gc.c
heaps.c
keyword.c
lexer.c
memory.c
method_def.c
operator.c
parser.c
position.c
result.c
string_reader.c
string_utils.c
syntax_error.c
to_string.c
token.c
value.c
whiskey.c
'''.split()

objects = env.Object(sources)
path_env = env.Clone(CCFLAGS = '-W -Wall -Wextra -I./include/')
objects += path_env.Object('path.c')

for subdir in env.subdirs:
    o = SConscript(subdir + '/SConscript', 'env')
    objects.append(o)

Return('objects')
