Import('env')

env = env.Clone()
env.Append(CPPPATH = '#/')

sources = '''
ast.c
class_def.c
dict.c
eval.c
gc.c
keyword.c
lexer.c
method_def.c
operator.c
parser.c
position.c
return_value.c
string_reader.c
string_utils.c
syntax_error.c
to_string.c
token.c
value.c
'''.split()

objects = env.Object(sources)

for subdir in env.subdirs:
    o = SConscript(subdir + '/SConscript', 'env')
    objects.append(o)

Return('objects')
